use std::fs;
use std::path::Path;
use std::env;
use pulldown_cmark::{Parser, Options, html};
use gray_matter::{Matter, engine::YAML};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct JekyllFrontMatter {
    layout: String,
    title: String,
    tags: String,
    category: String,
}

#[derive(Debug)]
struct ProcessedPost {
    slug: String,
    title: String,
    tags: Vec<String>,
    category: String,
    layout: String,
    html_content: String,
    original_filename: String,
}

fn main() {
    let posts_dir = Path::new("../_posts");
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("posts.rs");
    
    // Process each markdown file
    let mut posts_data = Vec::new();
    
    if posts_dir.exists() {
        for entry in fs::read_dir(posts_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            
            if path.extension().map_or(false, |ext| ext == "md") {
                let content = fs::read_to_string(&path).unwrap();
                if let Some(processed) = process_markdown_file(&content, &path) {
                    posts_data.push(processed);
                }
            }
        }
    }
    
    // Sort posts by filename (newest first)
    posts_data.sort_by(|a, b| b.original_filename.cmp(&a.original_filename));
    
    // Generate posts.rs
    generate_posts_module(&posts_data, &dest_path);
    
    // Tell Cargo to rerun if markdown files change
    println!("cargo:rerun-if-changed=../_posts");
}

fn process_markdown_file(content: &str, path: &Path) -> Option<ProcessedPost> {
    let matter = Matter::<YAML>::new();
    let result = matter.parse(content);
    
    // Skip if no frontmatter
    let frontmatter: JekyllFrontMatter = result.data?.deserialize().ok()?;
    
    // Convert Jekyll's space-separated tags to Vec<String>
    let tags: Vec<String> = frontmatter.tags
        .split_whitespace()
        .map(|s| s.to_string())
        .collect();
    
    // Parse markdown content (everything after frontmatter)
    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_FOOTNOTES);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_TASKLISTS);
    
    let parser = Parser::new_ext(&result.content, options);
    let mut html = String::new();
    html::push_html(&mut html, parser);
    
    Some(ProcessedPost {
        slug: extract_slug_from_filename(path),
        title: frontmatter.title,
        tags,
        category: frontmatter.category,
        layout: frontmatter.layout,
        html_content: html,
        original_filename: path.file_name().unwrap().to_str().unwrap().to_string(),
    })
}

fn extract_slug_from_filename(path: &Path) -> String {
    let filename = path.file_stem().unwrap().to_str().unwrap();
    // Remove Jekyll date prefix: "2024-01-06-euler-sql-2" -> "euler-sql-2"
    let parts: Vec<&str> = filename.split('-').collect();
    if parts.len() >= 4 {
        // Skip first 3 parts (YYYY-MM-DD) and join the rest
        parts[3..].join("-")
    } else {
        filename.to_string()
    }
}

fn generate_posts_module(posts: &[ProcessedPost], dest_path: &Path) {
    let mut module_content = String::new();
    
    module_content.push_str("// Auto-generated by build.rs\n\n");
    
    // Generate post content constants
    for post in posts {
        let const_name = format!("POST_{}", post.slug.to_uppercase().replace("-", "_"));
        // Ensure const name starts with a letter
        let const_name = if const_name.chars().next().map_or(false, |c| c.is_ascii_digit()) {
            format!("P{}", const_name)
        } else {
            const_name
        };
        
        module_content.push_str(&format!(
            "const {}_HTML: &str = r#\"{}\"#;\n\n",
            const_name,
            post.html_content.replace("\\", "\\\\").replace("\"", "\\\"")
        ));
    }
    
    // Generate posts data function
    module_content.push_str("pub fn get_posts() -> Vec<Post> {\n");
    module_content.push_str("    vec![\n");
    
    for post in posts {
        let const_name = format!("POST_{}", post.slug.to_uppercase().replace("-", "_"));
        let const_name = if const_name.chars().next().map_or(false, |c| c.is_ascii_digit()) {
            format!("P{}", const_name)
        } else {
            const_name
        };
        
        let tags_str = post.tags.iter()
            .map(|t| format!("\"{}\".to_string()", t))
            .collect::<Vec<_>>()
            .join(", ");
        
        module_content.push_str(&format!(
            "        Post {{\n            title: \"{}\".to_string(),\n            slug: \"{}\".to_string(),\n            tags: vec![{}],\n            category: \"{}\".to_string(),\n            layout: \"{}\".to_string(),\n            html_content: {}_HTML.to_string(),\n            original_filename: \"{}\".to_string(),\n            preview: \"\".to_string(),\n        }},\n",
            post.title.replace("\"", "\\\""),
            post.slug,
            tags_str,
            post.category,
            post.layout,
            const_name,
            post.original_filename
        ));
    }
    
    module_content.push_str("    ]\n}\n");
    
    fs::write(dest_path, module_content).unwrap();
}