use std::fs;
use std::path::Path;
use std::env;
use pulldown_cmark::{Parser, Options, html, Event, Tag, TagEnd, CodeBlockKind};
use gray_matter::{Matter, engine::YAML};
use serde::Deserialize;
use syntect::html::{ClassedHTMLGenerator, ClassStyle};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

#[derive(Debug, Deserialize)]
struct JekyllFrontMatter {
    layout: String,
    title: String,
    tags: String,
    category: String,
}

#[derive(Debug)]
struct ProcessedPost {
    slug: String,
    title: String,
    tags: Vec<String>,
    category: String,
    layout: String,
    html_content: String,
    original_filename: String,
}

fn main() {
    let posts_dir = Path::new("../_posts");
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("posts.rs");
    
    // Create posts-html directory
    let posts_html_dir = Path::new("posts-html");
    if !posts_html_dir.exists() {
        fs::create_dir_all(posts_html_dir).unwrap();
    }
    
    // Process each markdown file
    let mut posts_data = Vec::new();
    
    if posts_dir.exists() {
        for entry in fs::read_dir(posts_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            
            if path.extension().map_or(false, |ext| ext == "md") {
                let content = fs::read_to_string(&path).unwrap();
                if let Some(processed) = process_markdown_file(&content, &path) {
                    // Generate HTML file for this post
                    generate_html_file(&processed, posts_html_dir);
                    posts_data.push(processed);
                }
            }
        }
    }
    
    // Sort posts by filename (newest first)
    posts_data.sort_by(|a, b| b.original_filename.cmp(&a.original_filename));
    
    // Generate posts.rs
    generate_posts_module(&posts_data, &dest_path);
    
    // Tell Cargo to rerun if markdown files change
    println!("cargo:rerun-if-changed=../_posts");
}

fn process_markdown_file(content: &str, path: &Path) -> Option<ProcessedPost> {
    let matter = Matter::<YAML>::new();
    let result = matter.parse(content);
    
    // Skip if no frontmatter
    let frontmatter: JekyllFrontMatter = result.data?.deserialize().ok()?;
    
    // Convert Jekyll's space-separated tags to Vec<String>
    let tags: Vec<String> = frontmatter.tags
        .split_whitespace()
        .map(|s| s.to_string())
        .collect();
    
    // Remove first H1 header to avoid title duplication
    let content_without_first_h1 = remove_first_h1(&result.content);
    
    // Parse markdown content (everything after frontmatter)
    let mut options = Options::empty();
    options.insert(Options::ENABLE_TABLES);
    options.insert(Options::ENABLE_FOOTNOTES);
    options.insert(Options::ENABLE_STRIKETHROUGH);
    options.insert(Options::ENABLE_TASKLISTS);
    
    let parser = Parser::new_ext(&content_without_first_h1, options);
    let html = markdown_to_html_with_syntax_highlighting(parser);
    
    Some(ProcessedPost {
        slug: extract_slug_from_filename(path),
        title: frontmatter.title,
        tags,
        category: frontmatter.category,
        layout: frontmatter.layout,
        html_content: html,
        original_filename: path.file_name().unwrap().to_str().unwrap().to_string(),
    })
}

fn extract_slug_from_filename(path: &Path) -> String {
    let filename = path.file_stem().unwrap().to_str().unwrap();
    // Remove Jekyll date prefix: "2024-01-06-euler-sql-2" -> "euler-sql-2"
    let parts: Vec<&str> = filename.split('-').collect();
    if parts.len() >= 4 {
        // Skip first 3 parts (YYYY-MM-DD) and join the rest
        parts[3..].join("-")
    } else {
        filename.to_string()
    }
}

fn generate_html_file(post: &ProcessedPost, posts_html_dir: &Path) {
    let html_filename = format!("{}.html", post.slug);
    let html_path = posts_html_dir.join(html_filename);
    
    // Write the HTML content to the file
    fs::write(html_path, &post.html_content).unwrap();
}

fn generate_posts_module(posts: &[ProcessedPost], dest_path: &Path) {
    let mut module_content = String::new();
    
    module_content.push_str("// Auto-generated by build.rs\n\n");
    
    // Generate posts data function
    module_content.push_str("pub fn get_posts() -> Vec<Post> {\n");
    module_content.push_str("    vec![\n");
    
    for post in posts {
        let tags_str = post.tags.iter()
            .map(|t| format!("\"{}\".to_string()", t))
            .collect::<Vec<_>>()
            .join(", ");
        
        // Generate a preview from the first 150 characters of HTML content
        let preview = {
            let text = post.html_content
                .replace("<p>", "")
                .replace("</p>", " ")
                .replace("<br>", " ")
                .replace("<br/>", " ")
                .replace("<br />", " ");
            let stripped = strip_html_tags(&text);
            if stripped.len() > 150 {
                format!("{}...", &stripped[..150])
            } else {
                stripped
            }
        };
        
        module_content.push_str(&format!(
            "        Post {{\n            title: \"{}\".to_string(),\n            slug: \"{}\".to_string(),\n            tags: vec![{}],\n            category: \"{}\".to_string(),\n            layout: \"{}\".to_string(),\n            html_content: \"{}\".to_string(),\n            original_filename: \"{}\".to_string(),\n            preview: \"{}\".to_string(),\n        }},\n",
            post.title.replace("\"", "\\\""),
            post.slug,
            tags_str,
            post.category,
            post.layout,
            escape_for_rust_string(&post.html_content),
            post.original_filename,
            preview.replace("\"", "\\\"").replace("\n", " ")
        ));
    }
    
    module_content.push_str("    ]\n}\n");
    
    fs::write(dest_path, module_content).unwrap();
}

fn markdown_to_html_with_syntax_highlighting(parser: Parser) -> String {
    let syntax_set = SyntaxSet::load_defaults_newlines();
    let mut html_output = String::new();
    let mut events = Vec::new();
    
    // Collect all events first
    for event in parser {
        events.push(event);
    }
    
    let mut i = 0;
    while i < events.len() {
        match &events[i] {
            Event::Start(Tag::CodeBlock(CodeBlockKind::Fenced(lang))) => {
                // Find the corresponding End event
                let mut depth = 1;
                let mut j = i + 1;
                let mut code_content = String::new();
                
                while j < events.len() && depth > 0 {
                    match &events[j] {
                        Event::Start(Tag::CodeBlock(_)) => depth += 1,
                        Event::End(TagEnd::CodeBlock) => depth -= 1,
                        Event::Text(text) => {
                            if depth == 1 {
                                code_content.push_str(text);
                            }
                        }
                        _ => {}
                    }
                    j += 1;
                }
                
                // Generate syntax highlighted HTML
                let highlighted_html = if !lang.is_empty() {
                    // Try to find syntax by token first, then by extension
                    let syntax = syntax_set.find_syntax_by_token(lang)
                        .or_else(|| syntax_set.find_syntax_by_extension(lang))
                        .or_else(|| {
                            // Handle common aliases
                            match lang.to_lowercase().as_str() {
                                "js" => syntax_set.find_syntax_by_extension("javascript"),
                                "ts" => syntax_set.find_syntax_by_extension("typescript"),
                                "py" => syntax_set.find_syntax_by_extension("python"),
                                "rb" => syntax_set.find_syntax_by_extension("ruby"),
                                "rs" => syntax_set.find_syntax_by_extension("rust"),
                                "sh" => syntax_set.find_syntax_by_extension("bash"),
                                "yml" => syntax_set.find_syntax_by_extension("yaml"),
                                "cs" => syntax_set.find_syntax_by_extension("csharp"),
                                "cpp" | "c++" => syntax_set.find_syntax_by_extension("cpp"),
                                "dockerfile" => syntax_set.find_syntax_by_name("Dockerfile"),
                                "json" => syntax_set.find_syntax_by_extension("json"),
                                "xml" => syntax_set.find_syntax_by_extension("xml"),
                                "html" => syntax_set.find_syntax_by_extension("html"),
                                "css" => syntax_set.find_syntax_by_extension("css"),
                                "scss" | "sass" => syntax_set.find_syntax_by_extension("scss"),
                                "sql" => syntax_set.find_syntax_by_extension("sql"),
                                "graphql" => syntax_set.find_syntax_by_extension("graphql"),
                                "toml" => syntax_set.find_syntax_by_extension("toml"),
                                "ini" => syntax_set.find_syntax_by_extension("ini"),
                                _ => None,
                            }
                        });
                    
                    match syntax {
                        Some(syntax) => {
                            let mut html_generator = ClassedHTMLGenerator::new_with_class_style(
                                syntax, &syntax_set, ClassStyle::Spaced
                            );
                            
                            for line in LinesWithEndings::from(&code_content) {
                                html_generator.parse_html_for_line_which_includes_newline(line).unwrap();
                            }
                            
                            format!("<pre class=\"highlight\"><code class=\"language-{}\">{}</code></pre>", 
                                lang, html_generator.finalize())
                        }
                        None => {
                            // Language not recognized, use plain text with language class
                            format!("<pre class=\"highlight\"><code class=\"language-{}\">{}</code></pre>", 
                                lang, escape_html(&code_content))
                        }
                    }
                } else {
                    format!("<pre class=\"highlight\"><code>{}</code></pre>", 
                        escape_html(&code_content))
                };
                
                html_output.push_str(&highlighted_html);
                i = j; // Skip to after the End event
            }
            _ => {
                // For all other events, use the standard HTML renderer
                let single_event = vec![events[i].clone()];
                let mut temp_html = String::new();
                html::push_html(&mut temp_html, single_event.into_iter());
                html_output.push_str(&temp_html);
                i += 1;
            }
        }
    }
    
    html_output
}

fn escape_html(input: &str) -> String {
    input
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn strip_html_tags(input: &str) -> String {
    let mut result = String::new();
    let mut in_tag = false;
    
    for ch in input.chars() {
        match ch {
            '<' => in_tag = true,
            '>' => in_tag = false,
            _ if !in_tag => result.push(ch),
            _ => {}
        }
    }
    
    result.trim().to_string()
}

fn escape_for_rust_string(input: &str) -> String {
    input
        .replace('\\', "\\\\")  // Escape backslashes first
        .replace('"', "\\\"")   // Escape quotes
        .replace('\n', "\\n")   // Escape newlines
        .replace('\r', "\\r")   // Escape carriage returns
        .replace('\t', "\\t")   // Escape tabs
}

fn remove_first_h1(content: &str) -> String {
    let lines: Vec<&str> = content.lines().collect();
    let mut result_lines = Vec::new();
    let mut found_first_h1 = false;
    
    for line in lines {
        if !found_first_h1 && line.trim_start().starts_with("# ") {
            found_first_h1 = true;
            continue; // Skip this line
        }
        result_lines.push(line);
    }
    
    result_lines.join("\n")
}